### PR TITLE
Add sassc dependency to Gemfile

### LINKED ISSUE #146: Include "sassc" gem in packed-mn
There are three remaining failures in the Tebako version due to https://github.com/metanorma/isodoc/issues/367. 

This is a bug in the metanorma-iso gem, that requires the “sassc” gem. The "sassc" gem requires "libsass" to be installed on Ubuntu.

However, it would be useful if we can package the “sassc” gem as well so that users can use custom SASS/SCSS files. 

This task is to include the "sassc" gem in the Gemfile, and "libsass" on Ubuntu.

_Originally posted by @ronaldtse in https://github.com/metanorma/packed-mn/issues/126#issuecomment-1009419301_

### PR DESCRIPTION
**Pull request by ronaldtse**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

Fixes #146

### CODE REVIEW

**Comment by ronaldtse** [comment]
There are two errors. We need to investigate -- I suspect both of them are related to sassc.

## Failure at sassc path location

So the compilation actually fails but job is marked complete for metanorma-iso
https://github.com/metanorma/packed-mn/runs/4770290111?check_suite_focus=true

The problem 
```
Metanorma XML Syntax: (XML Line 000136:125): IDREF "foreword" without matching ID
Metanorma XML Syntax: (XML Line 000136:125): IDREF "foreword" without matching ID
Error: File to import not found or unreadable: base_style/all.scss.
        on line 18:1 of stdin
>> @import 'base_style/all';

   ^
stdin:18
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/css.rb:88:in `convert_scss'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/css.rb:100:in `generate_css'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/css.rb:28:in `populate_css'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/html_function/html.rb:12:in `block (2 levels) in convert1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:433:in `insert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:416:in `method_missing'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/html_function/html.rb:10:in `block in convert1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:334:in `initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:292:in `new'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:292:in `with'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:33:in `noko'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/html_function/html.rb:9:in `convert1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/isodoc/iso/base_convert.rb:13:in `convert1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/convert.rb:182:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/html_convert.rb:26:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/metanorma/iso/processor.rb:50:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:199:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:191:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

## Segfault in ubuntu-20.04 and metanorma-iso

```
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:152: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0026 p:---- s:0182 e:000181 CFUNC  :parse
c:0025 p:0006 s:0170 e:000169 METHOD /__tebako_memfs__/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32
c:0024 p:0018 s:0161 e:000160 METHOD /__tebako_memfs__/lib/ruby/2.7.0/psych/nodes/node.rb:50
c:0023 p:0066 s:0157 e:000156 METHOD /__tebako_memfs__/lib/ruby/2.7.0/psych.rb:279
c:0022 p:---- s:0145 e:000144 CFUNC  :map
c:0021 p:0030 s:0141 e:000140 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:213
c:0020 p:0077 s:0133 e:000132 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:21
c:0019 p:0011 s:0128 e:000124 BLOCK  /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:17 [FINISH]
c:0018 p:---- s:0120 e:000119 CFUNC  :each
c:0017 p:0054 s:0116 e:000115 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:16
c:0016 p:0042 s:0111 e:000110 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:10
c:0015 p:0022 s:0103 e:000102 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:55 [FINISH]
c:0014 p:---- s:0095 e:000094 CFUNC  :new
c:0013 p:0027 s:0088 e:000087 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/isodoc/iso/init.rb:19
c:0012 p:0103 s:0081 e:000080 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/convert.rb:171
c:0011 p:0056 s:0069 e:000068 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/convert.rb:181
c:0010 p:0022 s:0057 e:000056 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/html_convert.rb:26
c:0009 p:0142 s:0048 e:000047 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/metanorma/iso/processor.rb:50
c:0008 p:0022 s:0039 e:000038 METHOD /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:199
c:0007 p:0012 s:0030 e:000029 BLOCK  /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:191
c:0006 p:0021 s:0023 e:000022 BLOCK  /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:11 [FINISH]
c:0005 p:---- s:0018 e:000017 CFUNC  :loop
c:0004 p:0005 s:0014 e:000013 BLOCK  /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:9 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :catch
c:0002 p:0007 s:0006 e:000005 BLOCK  /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:8 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:191:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.4/lib/metanorma/compile.rb:199:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/metanorma/iso/processor.rb:50:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/html_convert.rb:26:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/convert.rb:181:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/convert.rb:171:in `convert_init'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/isodoc/iso/init.rb:19:in `i18n_init'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/isodoc/iso/init.rb:19:in `new'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:55:in `initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:10:in `load_yaml'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:16:in `normalise_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:16:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:17:in `block in normalise_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:16:in `normalise_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:16:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:17:in `block in normalise_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/i18n.rb:21:in `normalise_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:213:in `cleanup_entities'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:213:in `map'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:213:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:213:in `each_slice'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:213:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/function/utils.rb:214:in `block in cleanup_entities'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/htmlentities-4.3.4/lib/htmlentities.rb:44:in `decode'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/htmlentities-4.3.4/lib/htmlentities.rb:44:in `new'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/htmlentities-4.3.4/lib/htmlentities/decoder.rb:6:in `initialize'
/bin/bash: line 5:  2572 Segmentation fault      (core dumped) build/bin/metanorma-linux-x86_64 site generate build/iso -c build/iso/metanorma.yml -o site/iso --agree-to-terms
make: *** [Makefile:37: test-flavor] Error 139
```

**Comment by maxirmx** [comment]
There are discussions regarding this or similar crashes that last for years
This one, for example: https://github.com/sass/sassc-ruby/issues/197 

Basically it is about multithreaded processing of not thread-safe array.

**Comment by ronaldtse** [comment]
(@opoudjis another reason why we shouldn't use SASS during document compilation)

**Comment by ronaldtse** [comment]
Thanks @maxirmx -- now the question is -- why is the sassc gem used in parallel?

**Comment by maxirmx** [comment]
I can probably make it work. Just a metter of time

**Comment by ronaldtse** [comment]
Thanks @maxirmx , yes please help try make it work. It’s strange that there are parallel accesses happening there.

**Comment by maxirmx** [comment]
Regarding the first issue:
```
Error: File to import not found or unreadable: base_style/all.scss.
        on line 18:1 of stdin
>> @import 'base_style/all';

   ^
stdin:18
```

The file is packaged into memfs as follows
```
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc/base_style/all.scss
```
but ruby does not attempt to open this file from memfs.   
So there shall be an issue with the following code from isodoc/css.rb. (or an issue with tebako supporting this code ...)
```
    def convert_scss(filename, stylesheet, stripwordcss)
      require "sassc"
      require "isodoc/sassc_importer"

      [File.join(Gem.loaded_specs["isodoc"].full_gem_path,
                 "lib", "isodoc"),
                 File.dirname(filename)].each do |name|
                   SassC.load_paths << name
                 end
                 SassC::Engine.new(scss_fontheader(stripwordcss) + stylesheet,
                                   syntax: :scss, importer: SasscImporter)
                   .render
    end
```

**Comment by ronaldtse** [comment]
Looks like Gem.loaded_specs is loaded with incorrect (non-memfs) paths. Maybe when we override ruby’s file loading mechanisms we also need to update the file paths used in ruby (for every gem loaded, Ruby keeps the location of that gem path, as technically ruby can load from multiple gem paths).

**Comment by maxirmx** [comment]
We do update file paths used in Ruby and all simple tests show that Gem loaded_spec points to correct location in memfs
This issue is something more specific. I am still struggling to reproduce it less complex environment.

**Comment by maxirmx** [comment]
load_paths is handled correctly
```
isodoc: SassC.load_paths << /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-1.8.4/lib/isodoc
isodoc: SassC.load_paths << /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-1.10.6/lib/isodoc/iso/html
```

The issue is that this gem opens files from native extension that does not know anything about memfs.
There are several options how to solve it (all bad):
- extract sassc files and subclass sassc module as it is done with ffi and seven_zip
- patch saasc extension statically (i.e. make a fork that is tebako-aware)
- patch sassc extension dynamically, which means first patch Ruby extbuilder

**Comment by maxirmx** [comment]
Hi, @ronaldtse 
I fixed sassc but it is another hack in addition to similar hacks for ffi, seven_zip_ruby and others 
I believe that generic solution is possible but it will take months to implement

**Comment by ronaldtse** [comment]
@maxirmx the builds seem to be failing right now. Can we fix this and merge? Thanks.

**Comment by maxirmx** [comment]
@ronaldtse 

Can you at least point me to the repo for this gem:

```
#<Thread:0x00007f4ebd440f58 /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/scrapper.rb:192:in `fetch_urn': undefined method `split' for nil:NilClass (NoMethodError)
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/scrapper.rb:181:in `fetch_docid'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/scrapper.rb:69:in `parse_page'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/hit.rb:13:in `fetch'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:177:in `isobib_results_filter'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:190:in `isobib_get1'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:42:in `get'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-iso-1.9.1/lib/relaton_iso/processor.rb:19:in `get'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:432:in `net_retry'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:417:in `new_bib_entry'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:397:in `check_bibliocache'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:74:in `fetch'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:110:in `block in fetch_async'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize
```

**Comment by ronaldtse** [comment]
Yes it is relaton/relaton. @andrew2net is the lead developer of Relaton. @andrew2net can you help @maxirmx with this? Thanks!

**Comment by andrew2net** [comment]
@maxirmx the repo is "relaton/relaton-iso".
The iso.org site was down from yesterday. It started work recently. Please try it again. I'll add rescue for this error in the next release.

**Comment by maxirmx** [comment]
I am now getting another error when TEST_FLAVOR is set to ogc
```
[relaton-ieee] ("IEEE Std 1516") fetching...
#<Thread:0x00007fe456202640 /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/__tebako_memfs__/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '' (JSON::ParserError)
	from /__tebako_memfs__/lib/ruby/2.7.0/json/common.rb:156:in `parse'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/hit_collection.rb:22:in `initialize'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/ieee_bibliography.rb:7:in `new'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/ieee_bibliography.rb:7:in `search'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/ieee_bibliography.rb:20:in `get'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/processor.rb:20:in `get'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:432:in `net_retry'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:417:in `new_bib_entry'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:397:in `check_bibliocache'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:74:in `fetch'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:110:in `block in fetch_async'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
Error: The action has timed out.
```

**Comment by ronaldtse** [comment]
@andrew2net any idea on the failure with OGC? Thanks.

**Comment by maxirmx** [comment]
There id some floating issue with file system that I am working on
It may affect other features as well

**Comment by maxirmx** [comment]
@ronaldtse I fixed some minor issues with tebako
Now we have only one issue --stable failure of ogc test. It is just failure to fetch a document
I noticed that windows and macos workflows are configured to ignore ogc test errors so I changed linux workflow to match others.
I am not sure if it is the desired state to do a merge.

**Comment by ronaldtse** [comment]
@maxirmx I think this is good to go. Let’s also move the gem hacks into Tebako so other ruby projects that use these gems can also work. 

Let’s temporarily ignore errors for OGC, then start a separate ticket to fix OGC and assign to @andrew2net. Thanks!

**Comment by andrew2net** [comment]
> @andrew2net any idea on the failure with OGC? Thanks.

The log shows the failure is with IEEE. The IEEE has changed its site template and API. I'll update relaton-ieee parser in the next relaton release 1.10

**Comment by ronaldtse** [comment]
Thanks @andrew2net for the clarification, I've now linked the issue https://github.com/relaton/relaton-ieee/issues/13 . Let's always track with issues so we all know what's going on. Keeping mentions in particular comments outside the repository won't work.

**Pull request merged**
