### PR TITLE
tebako v0.3.9

### PR DESCRIPTION
**Pull request by maxirmx**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by maxirmx** [comment]
In this PR I have implemented manual libarchive setup thriugh the whole toolchain thus avoiding packaging issues
Thanks

**Review by CAMOBAP — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@maxirmx the Windows build job seems to have failed?

**Comment by maxirmx** [comment]
> @maxirmx the Windows build job seems to have failed?

@ronaldtse I believe it is a separate issue: https://github.com/metanorma/packed-mn/issues/185

**Comment by maxirmx** [comment]
@ronaldtse @CAMOBAP 
UPD
It looks like ocra packaging is broken.  
- It fails to load ffi
```
C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1188:in `initialize': No such file or directory @ rb_sysopen - C:/hostedtoolcache/windows/Ruby/2.7.7/x64/bin/ruby_builtin_dlls/libffi-7.dll (Errno::ENOENT)
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1188:in `open'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1188:in `createfile'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:938:in `block (2 levels) in build_exe'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:936:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:936:in `block in build_exe'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1087:in `block in initialize'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1071:in `open'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1071:in `initialize'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:879:in `new'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:879:in `build_exe'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/ocra-1.3.11/bin/ocra:1231:in `block in <top (required)>'
```
- It creates a package that has  ~ 300 kB size (shall be ~ 100 Mb)
- It fails at internal signature check when the package is started: FATAL ERROR: Bad signature in executable.

**Pull request merged**
