### PR TITLE
Replace seven_zip_ruby reference with seven-zip

### PR DESCRIPTION
**Pull request by maxirmx**
(due to introduction of  seven-zip gem aka https://github.com/fontist/seven_zip_ruby)

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Seems that the builds are failing at:

```
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/seven-zip-1.4.1/lib/seven_zip_ruby.rb:26:in `<top (required)>': Failed to initialize SevenZipRuby (RuntimeError)
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.1/lib/excavate/extractors/seven_zip_extractor.rb:1:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.1/lib/excavate/extractors.rb:7:in `require_relative'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.1/lib/excavate/extractors.rb:7:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.1/lib/excavate.rb:4:in `require_relative'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/excavate-0.3.1/lib/excavate.rb:4:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.14.3/lib/fontist/font_installer.rb:2:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.14.3/lib/fontist/font.rb:1:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.14.3/lib/fontist.rb:11:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:5:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.4.12/lib/metanorma.rb:11:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.22/lib/metanorma/cli.rb:3:in `<top (required)>'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	from /__tebako_memfs__/local/metanorma:209:in `<main>'
/__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- metanorma/cli (LoadError)
	from /__tebako_memfs__/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /__tebako_memfs__/local/metanorma:209:in `<main>'
```

**Comment by ronaldtse** [comment]
At least we now have the freedom to update the seven-zip gem to address these issues directly. We do want to drop all the hacks in the `bin/metanorma` file.

**Comment by maxirmx** [comment]
No, we can not do it without a hack in existing architecture
Please refer to the number 5 here:
https://github.com/tamatebako/tebako/issues/42#issuecomment-1018498412

We still have several options to avoid it in the future but it cannot be fixed by Gem changes

**Comment by ronaldtse** [comment]
@maxirmx understand, let's proceed then.

**Pull request merged**
