### PR TITLE
#102 update ruby-packer to 0.4.7

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #102

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Looks like 0.4.7 use ruby-2.4.4, not ruby-2.5.1. @alexeymorozov could you please confirm?

**Comment by alexeymorozov** [comment]
@CAMOBAP Yes, v0.4.7 uses Ruby 2.4.4. To use Ruby 2.5.1 please use [v0.5.0](https://github.com/metanorma/ruby-packer/releases/tag/v0.5.0), it was released today.

**Comment by ronaldtse** [comment]
@camobap some failures, I'm not sure if they are real:

* NIST/BSI flavors failing due to missing `sassc` gem:
```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/isodoc-1.6.3/lib/isodoc/css.rb:78:in `require': cannot load such file -- sassc (LoadError)
1007
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/isodoc-1.6.3/lib/isodoc/css.rb:78:in `convert_scss'
1008
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/isodoc-1.6.3/lib/isodoc/css.rb:100:in `generate_css'
1009
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/isodoc-1.6.3/lib/isodoc/css.rb:28:in `populate_css'
1010
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.5.0/gems/isodoc-1.6.3/lib/isodoc/html_function/html.rb:10:in `block (2 levels) in convert1'
1011
```

* Windows build failing

**Comment by ronaldtse** [comment]
But the gems are not supposed to require `sassc` gem. Ping @opoudjis .

**Comment by opoudjis** [comment]
Gems require sassc if you pull them from github, not if you run them from released version; is that what's going on here?

**Comment by ronaldtse** [comment]
@opoudjis possibly, but the `require` is from `isodoc`:
```
isodoc-1.6.3/lib/isodoc/css.rb:78:in `require': cannot load such file -- sassc (LoadError)
```

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis as far as I understood, before publishing to rubygems.org we do `scss` -> `css` conversion somehow.

There is no relevant logic in `Rakefile`s, @opoudjis maybe you can confirm my assumption and explain how we can do this, so I will automate this

**Comment by CAMOBAP** [comment]
Got all answers, thanks to @opoudjis

**Comment by CAMOBAP** [comment]
Both macOS and Linux are good

I still working on windows/OCRA related issues...

**Comment by CAMOBAP** [comment]
Current error 

C:/Users/IEUser/AppData/Local/Temp/ocrD702.tmp/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': 126: The specified module could not be found.   - C:/Users/IEUser/AppData/Local/Temp/ocrD702.tmp/lib/ruby/2.7.0/x64-mingw32/openssl.so (LoadError)

Trounleshooting...

**Comment by CAMOBAP** [comment]
Next issue https://github.com/larsch/ocra/issues/174

**Comment by ronaldtse** [comment]
@CAMOBAP what has changed in Ocra that it no longer works?

**Comment by CAMOBAP** [comment]
@ronaldtse no changes in ocra by itself, but we changed ruby version from 2. to 2.5

**Comment by ronaldtse** [comment]
Got it, thanks @CAMOBAP !

**Comment by CAMOBAP** [comment]
@ronaldtse finally the OCRA issue looks solved

But I have found out one serious problem `metanorma` will not work correctly if `Gemfile` is in current directory. This is why I added `rm Gemfile` as a workaround

We rarely faced with this issue before, but now it happens constantly because we use 'private' gem from github

My proposal to investigate this issue separately

**Comment by ronaldtse** [comment]
Makes sense. Thank you for tackling this issue @CAMOBAP !

**Pull request merged**
