### PR TITLE
Upgrade build runner from 18.04 to 20.04

### PR DESCRIPTION
**Pull request by CAMOBAP**
Related issues:
 - https://github.com/metanorma/emf2svg-ruby/issues/37

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@maxirmx maybe you can quick look at the issue in this PR

`/home/runner/work/packed-mn/packed-mn/.archive/tebako/deps/bin/mkdwarfs: error while loading shared libraries: libboost_context.so.1.65.1: cannot open shared object file: No such file or directory`

**Comment by maxirmx** [comment]
I think the cache did not invalidate automatically on OS version change
I bumped cache manually. Even if it was the reason I do not think it is worth automation.

**Comment by ronaldtse** [comment]
> I think the cache did not invalidate automatically on OS version change
> I bumped cache manually. Even if it was the reason I do not think it is worth automation.

At least there is an easy way now to clean cache on GH!

**Comment by maxirmx** [comment]
@CAMOBAP 
I think that explicit jemalloc build was also Ubuntu 18 requirement.  Let me look at it, it is really annoyning

**Comment by CAMOBAP** [comment]
@maxirmx @ronaldtse build step is passed successfully so I think we can safely merge this PR. I'm going to do this

**Pull request merged**
