### PR TITLE
metanorma/metanorma-snap#22 build libsaasc with static stdlibc++

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-snap#22
 - https://github.com/metanorma/packed-mn/pull/56#issuecomment-1126908378

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@maxirmx maybe there is a way to unpack/extract the final executable to check its content?

**Comment by maxirmx** [comment]
> @maxirmx maybe there is a way to unpack/extract the final executable to check its content? Or maybe it possible somehow to enable verbose sollging for tebako to show details on `bundle install`

@CAMOBAP 
1. There is a limitation of underlying library that does not allow to unpack or extract final executable (there was thi feature request -- https://github.com/tamatebako/tebako/issues/22   the third item).   I will implement a solution for it in 2-3 days.

2. packed-mn GHA build step leaves folder/files that were packed at  ```.archive/tebako/output/source_filesystem``` 
We can pack it with tar.gz   and upload as GHA artifact for further inspection

**Comment by CAMOBAP** [comment]
Thanks @maxirmx for packing source fs, with it I just confirmed that this PR works

Before PR:
Screen Shot 2022-05-18 at 8 59 48 AM

After PR:
Screen Shot 2022-05-18 at 9 00 06 AM

I will restart failed jobs and merge

**Comment by maxirmx** [comment]
I am merging tebako version that has this capability built-in
I hope it wil be easier to use it in the future

**Pull request merged**
