### PR TITLE
Bugfix/failed to initialize sevenzipruby

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #83

P.S. Each time those new hacks and workaround scares me more and more)

### CODE REVIEW

**Comment by CAMOBAP** [comment]
The original issue is fixed but a new one discovered:

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.15.0/lib/ffi/struct_layout.rb:88:in `get': invalid memory read at address=0x00000000000000 (FFI::NullPointerError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.15.0/lib/ffi/struct_layout.rb:88:in `get'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.10.1/lib/libmspack/mscab.rb:305:in `[]'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.10.1/lib/libmspack/mscab.rb:305:in `files'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors/cab_extractor.rb:8:in `block in extract'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors/cab_extractor.rb:26:in `open_cab'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors/cab_extractor.rb:7:in `extract'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:71:in `rescue in extract_once'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:63:in `extract_once'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:53:in `extract_recursively'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:76:in `extract_and_replace'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:58:in `block in extract_recursively'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:55:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:55:in `extract_recursively'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:76:in `extract_and_replace'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:58:in `block in extract_recursively'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:55:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:55:in `extract_recursively'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:33:in `extract'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/archive.rb:18:in `files'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:49:in `block in install_fonts_from_archive'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:48:in `tap'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:48:in `install_fonts_from_archive'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:42:in `extract'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:23:in `block in install_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:31:in `block in run_in_temp_dir'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:28:in `run_in_temp_dir'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:23:in `install_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:15:in `install'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:119:in `block in download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:117:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:117:in `flat_map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:117:in `download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:44:in `install'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:24:in `install'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/install.rb:24:in `install_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/install.rb:18:in `file_paths'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:50:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:50:in `style_paths'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:38:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:38:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:38:in `font_paths'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:26:in `call'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/manifest/locations.rb:21:in `from_hash'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:317:in `fontist_install'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:295:in `install_fonts_safe'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:313:in `rescue in install_fonts_safe'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:295:in `install_fonts_safe'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:289:in `install_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:27:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:77:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:24:in `block in generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:24:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:24:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:19:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/commands/site.rb:23:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli.rb:67:in `start'
	from /__enclose_io_memfs__/local/metanorma:198:in `<main>'
```

TODO check if this related to https://github.com/metanorma/metanorma-iso/issues/479

**Review by w00lf — APPROVED** [review]
Lgtm

**Comment by CAMOBAP** [comment]
I have tried to reproduce the issue on a minimal sample unfortunately it doesn't reproduced there

- `wget https://gitlab.com/fontmirror/archive/-/raw/master/PowerPointViewer.exe`
- run `extract_cleartype.rb`

<details><summary>extract_cleartype.rb</summary>
<p>

#### yes, even hidden code blocks!

```ruby
#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
require "tmpdir"

COMPILER_MEMFS = "/__enclose_io_memfs__"

unless Gem.win_platform? # because on windows we use ocra
  # https://github.com/pmq20/ruby-packer/blob/master/lib/compiler/constants.rb#L10
  COMPILER_MEMFS_LIB_CACHE = Pathname.new(Dir.mktmpdir("packed-mn-"))
  at_exit {
    FileUtils.remove_dir(COMPILER_MEMFS_LIB_CACHE.to_path, true)
  }

  class String
    def is_quoted
      self.start_with?('"') && self.end_with?('"')
    end

    def unquote
      self.chomp('"').reverse.chomp('"').reverse
    end

    def quote
      "\"#{self}\""
    end
  end

  def extract_memfs(file, wild=false, extract_path=COMPILER_MEMFS_LIB_CACHE)
    is_quoted = file.is_quoted
    file = file.unquote if is_quoted

    return file unless file.start_with? COMPILER_MEMFS

    memfs_extracted_file = extract_path + File.basename(file)
    unless memfs_extracted_file.exist?
      if wild
        files = Dir.glob("#{File.dirname(file)}/*#{File.extname(file)}")
        FileUtils.cp_r files, extract_path
      else
        FileUtils.cp file, memfs_extracted_file
      end
    end

    is_quoted ? memfs_extracted_file.to_path.quote : memfs_extracted_file.to_path
  end

  # HACK: extract temp libraries to use with ffi
  # Wrapper for FFI.map_library_name method
  require 'ffi'
  require 'pathname'

  module FFI
    # https://stackoverflow.com/questions/29907157/how-to-alias-a-class-method-in-rails-model/29907207
    self.singleton_class.send(:alias_method, :map_library_name_orig, :map_library_name)

    # http://tech.tulentsev.com/2012/02/ruby-how-to-override-class-method-with-a-module/
    def self.map_library_name(lib)
      map_library_name_orig(extract_memfs(lib))
    end
  end
  # END of HACK
end

require "libmspack"
require "fileutils"

CAB_FILE = File.join("tmp", "ppviewer.cab")
FileUtils.mkdir_p("tmp")

decompressor = LibMsPack::CabDecompressor.new

unless File.exists?(CAB_FILE)
  cab = decompressor.search("./PowerPointViewer.exe")
  file = cab.files

  while file
    if file.filename == "ppviewer.cab"
      path = File.join("tmp", file.filename)
      decompressor.extract(file, path)
    end
    file = file.next
  end
end

cab = decompressor.search(CAB_FILE)
file = cab.files

while file
  p file.filename

  if file.filename.downcase.end_with?(".ttf")
    path = File.join("tmp", file.filename)
    decompressor.extract(file, path)
  end

  file = file.next
end

```

</p>
</details>

**Comment by CAMOBAP** [comment]
Windows related issue will be addressed in the scope of https://github.com/metanorma/packed-mn/issues/80

**Pull request merged**
