### PR TITLE
Hotfix v0.0.8: gem dependencies update, fix typos

### PR DESCRIPTION
**Pull request by w00lf**
#12 
Tried to also update metanorma-nist but encountered an error with this line of code: https://github.com/metanorma/metanorma-nist/blob/master/lib/isodoc/nist/html/htmlstyle.scss#L21, such import is not working with a compiled version of the application.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Ping @opoudjis @strogonoff .

**Comment by opoudjis** [comment]
This is @strogonoff 's refactor, but I guess I'm responsible for it now.

I have zero context or idea of what this is and why this would not work, and @w00lf you will need to provide me with a lot more context in general. But: this is meant to inherit at that line from CSS stylesheets defined in the isodoc gem, which is where `@import 'base_style/all';` is defined: https://github.com/metanorma/isodoc/blob/master/lib/isodoc/base_style/all.scss . All HTML CSS in the stack is being refactored to inherit from isodoc/base_style, and this has already been done for the CSD and NIST gem.

All CSS is processed in https://github.com/metanorma/isodoc/blob/master/lib/isodoc/convert.rb:

````
 def generate_css(filename, stripwordcss, fontheader)
      return nil unless filename
      stylesheet = File.read(filename, encoding: "UTF-8")
      stylesheet = populate_template(stylesheet, :word)
      stylesheet.gsub!(/(\s|\{)mso-[^:]+:[^;]+;/m, "\\1") if stripwordcss
      SassC.load_paths << File.join(Gem.loaded_specs['isodoc'].full_gem_path,
                                    "lib", "isodoc")
      SassC.load_paths << File.dirname(filename)
      engine = SassC::Engine.new(fontheader + stylesheet, syntax: :scss)
      outname = File.basename(filename, ".*") + ".css"
      File.open(outname, "w:UTF-8") { |f| f.write(engine.render) }
      @files_to_delete << outname
      outname
    end
````

As you can see, SassC.load_paths is used to ensure that the current gem sees the contents of isodoc for paths.

If you are processing these stylesheets outside the context of that function call, which uses both SassC and Liquid to populate the stylesheets (the latter populating it with document-specific metadata), then what you are doing is going to fail.

**Comment by opoudjis** [comment]
@w00lf If you need something from me and I don't respond in a couple of days, ping me on Skype. I am (a) very busy, and (b) all over the place as (I guess) dev lead, so i do not check my notifications daily.

**Comment by ronaldtse** [comment]
@w00lf could you add the particular check to the GitHub Action test so that it will fail when it's not working? Thanks.

**Comment by w00lf** [comment]
> @w00lf If you need something from me and I don't respond in a couple of days, ping me on Skype. I am (a) very busy, and (b) all over the place as (I guess) dev lead, so i do not check my notifications daily.

Hi there @opoudjis . So about this particular error that i mentioned before. Currently we are using ruby-packer gem to compile all metanorma cli project in one executable than can be distributed as one file to different platforms. This gem has some specific issues in it. First, it creates an in-memory file system using squash fs tool, this file system is read-only and consists patched version of ruby interpretatior. This interpretatior has patched versions of File and Dir classes: when application requests path starting from /__enclosed_mem_fs__/ it is redirected to in-memory file system. Thts how it works on every platform. However, if there is any lookup method that is not patched like this it will fail, that's what happens with this css file lookup.

**Comment by ronaldtse** [comment]
@w00lf it seems like the redirection failure happens in SassC?

In particular these lines here:
https://github.com/metanorma/isodoc/blob/master/lib/isodoc/convert.rb

```ruby
      SassC.load_paths << File.join(Gem.loaded_specs['isodoc'].full_gem_path,
                                    "lib", "isodoc")
      SassC.load_paths << File.dirname(filename)
```

Maybe the patch for SassC isn't fully working?

**Comment by ronaldtse** [comment]
@w00lf can we merge this and deal with this SassC problem in a new issue?

**Comment by w00lf** [comment]
> @w00lf can we merge this and deal with this SassC problem in a new issue?

Yes of course. Its only affects the version of gem sassc used.

**Comment by ronaldtse** [comment]
Thanks @w00lf !

**Pull request merged**
