### PR TITLE
Install clang explicitly

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #57

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP the latest rubyc from ruby-packer executable doesn't work -- we need to use the original 2.4 version.

**Comment by ronaldtse** [comment]
We should have never depended on the `rubyc` executable on enclose.io. Now the whole process if screwed.

**Comment by ronaldtse** [comment]
@CAMOBAP can you help update the macOS binary? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse I'm preparing Linux right now should be done in next 1h, thanks @w00lf for the suggestion

So I will fix both at once

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
macOS works!

**Comment by ronaldtse** [comment]
@w00lf do you have the old linux binary? If so can you upload here: https://github.com/metanorma/ruby-packer/releases/tag/v0.4.0 ? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse I just build it on GHA, unfortunately, wasn't managed to build it inside of docker, should be fixed for Linux really soon

**Comment by pmq20** [comment]
@ronaldtse Sorry enclose.io broke down last weekend due to Heroku usage limit. I plan to rewrite that web service and pay for a higher level Heroku plan soon.

**Comment by ronaldtse** [comment]
Thanks @pmq20 , GitHub releases usually helps resolve these issues, especially for CI builds because of the number of times a binary is downloaded. On the other hand, I’ve also sent you an email before, let me know what you think!

**Comment by ronaldtse** [comment]
@CAMOBAP do we still need this? The Linux build seems to be completed (does it work?)

**Comment by CAMOBAP** [comment]
I did some workflow refactoring in the scope of this, so please let me finish it

**Comment by ronaldtse** [comment]
@CAMOBAP OK, feel free to merge when ready.

**Comment by ronaldtse** [comment]
@CAMOBAP it all passes now!! Thanks!!

**Pull request merged**
