### PR TITLE
Feature/ieee test

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #173

### CODE REVIEW

**Comment by maxirmx** [comment]
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

I beleive Macos 10.15 runner is down today and will be fully decomissioned soon

**Comment by CAMOBAP** [comment]
> https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
> 
> I beleive Macos 10.15 runner is down today and will be fully decomissioned soon

I will try to update to macos 11

**Comment by maxirmx** [comment]
There was a requirement to be 10.15 compatible
Anyway, if you are moving to macos-latest it is not the same as macos-11 since you can jump to 12 unexpectedly
Also you need XCode version that is supported by the action we use to setup it.  I would try 12.5.1

**Comment by CAMOBAP** [comment]
> There was a requirement to be 10.15 compatible

@ronaldtse if we still need this probably we should setup own runner or maybe there are some third-party ones

> Anyway, if you are moving to macos-latest it is not the same as macos-11 since you can jump to 12 unexpectedly

Agree, I changed to `macos-11`

> Also you need XCode version that is supported by the action we use to setup it. I would try 12.5.1

I choose `12.4` because if used in tabtebaco's CI https://github.com/tamatebako/tebako/blob/main/.github/workflows/macos.yml#L80-L84 should we still give a shot `12.5.1`?

**Comment by maxirmx** [comment]
> @ronaldtse if we still need this probably we should setup own runner or maybe there are some third-party ones
I can try to build on 11 for 10.15 target.  There was some issue with it so it will take some time

> Agree, I changed to `macos-11`
+
 
> I choose `12.4` because if used in tabtebaco's CI https://github.com/tamatebako/tebako/blob/main/.github/workflows/macos.yml#L80-L84 should we still give a shot `12.5.1`?

You are right. Pls keep 12.4 here and  and I will try 12.5.1 in tebako

**Comment by CAMOBAP** [comment]
> I can try to build on 11 for 10.15 target. There was some issue with it so it will take some time

@maxirmx should I create a separate ticket for this, or maybe this can be done in the scope of this PR?

**Comment by maxirmx** [comment]
> > I can try to build on 11 for 10.15 target. There was some issue with it so it will take some time
> 
> @maxirmx should I create a separate ticket for this, or maybe this can be done in the scope of this PR?

https://github.com/tamatebako/tebako/issues/85
It won't be fast

**Review by maxirmx — APPROVED** [review]

**Pull request merged**
