### PR TITLE
#55 Downgrade libstdc++ ABI version requirments

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #55

### CODE REVIEW

**Comment by ronaldtse** [comment]
Does this work on Ubuntu 18.04?

**Comment by ronaldtse** [comment]
@CAMOBAP we should not need sassc for build anymore here.

**Comment by CAMOBAP** [comment]
@ronaldtse actually we still use sassc so we need to statically link libstdc++ in the native extension to avoid this issue, I will prepare separate PR

**Comment by ronaldtse** [comment]
@CAMOBAP can you ask @maxirmx for help with this issue? Thanks.

**Comment by CAMOBAP** [comment]
> @CAMOBAP can you ask @maxirmx for help with this issue? Thanks.

I already know (have a plan) how it can be fixed, so I will provide PR today, In case of stuck or need a hand I will ask @maxirmx

**Comment by ronaldtse** [comment]
@CAMOBAP thanks! 👍

**Pull request closed without merging**
