### PR TITLE
Bugfix/windows upload zerofiles

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP the fact that there is a zero-length file means there is some serious error in Metanorma processing. We need to find out which file it is and fix the problem.

**Comment by ronaldtse** [comment]
@CAMOBAP FYI the issue about the broken PDF file is filed here: https://github.com/metanorma/metanorma-ogc/issues/332

We might not want to avoid the zero-length issue as it is a real problem.

What we should fix instead is that if PDF processing fails we must fail the whole processing chain.

**Comment by CAMOBAP** [comment]
> We might not want to avoid the zero-length issue as it is a real problem.

Agree but this issue should be handled on metanorma-cli or metanorma-ogc level, not here.

BTW here is a ticket for 0-bytes file upload for windows https://github.com/actions/upload-artifact/issues/281

One thing which I want to improve to not fail on timeout, @ronaldtse is it make sense?

**Comment by CAMOBAP** [comment]
No built-in way to do this (check if timeout happens), I propose to merge this

@ronaldtse how do you think?

**Pull request merged**
