### PR TITLE
#71 update vendor/cacert.pem.mozilla

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #71

### CODE REVIEW

**Comment by ronaldtse** [comment]
Builds seem to be failing. @w00lf thoughts on the actual certificate change?

**Comment by w00lf** [comment]
> Builds seem to be failing. @w00lf thoughts on the actual certificate change?

The error occurs during the build itself, it could be that the build image has updated SSL certs list and packed-mn does not support it.

**Comment by CAMOBAP** [comment]
We cannot change/update bundler version. Looks like we need to update cert 'manually' looking for some script for this https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-ca-certificates

**Comment by CAMOBAP** [comment]
What I have found so far:
 - issue happens with bundler 1.15.3 which is frozen for the rubyc which we used
 - we cannot upgrade bundler
 - I didn't found a way to install certs somehow into rubyc

I'm working on last point

**Comment by CAMOBAP** [comment]
Well, I don't see other option then patch `rubyc` to update the embedded bundler gem version from 1.15.3 to 2.x

@w00lf may I kindly ask you to remind us why we use `rubyc@0.4.0` version instead of the latest one? AFAIR there is some known issue which hurts us

**Comment by ronaldtse** [comment]
> Well, I don't see other option then patch `rubyc` to update the embedded bundler gem version from 1.15.3 to 2.x
> 
> @w00lf may I kindly ask you to remind us why we use `rubyc@0.4.0` version instead of the latest one? AFAIR there is some known issue which hurts us

I remember because ruby-packer at any other version gives us segfaults.

**Comment by CAMOBAP** [comment]
As I see some commits were pushed to https://github.com/pmq20/ruby-packer/commits/master. @w00lf @ronaldtse how do you think, should we try it again?

**Comment by w00lf** [comment]
> Well, I don't see other option then patch `rubyc` to update the embedded bundler gem version from 1.15.3 to 2.x
> 
> @w00lf may I kindly ask you to remind us why we use `rubyc@0.4.0` version instead of the latest one? AFAIR there is some known issue which hurts us

Hi there, the issue here was in `rubyc` stability. The latest release was not fully functional, I tried to use it and its gave compile errors that was not been able to address, also memory consumption was even worse than 0.4.0 version, so I decided to go with this stable version. Now, about bundler internally update, the issue here will be in specific of `rubyc` application itself -  internally it uses patched ruby version in order to properly compile and link all modules. Because of that any updates performed to it need additional tweaks to clang code of the application ruby. In theory, we can try to upgrade bundler version, but that's no easy task to do.

**Comment by w00lf** [comment]
> As I see some commits were pushed to https://github.com/pmq20/ruby-packer/commits/master. @w00lf @ronaldtse how do you think, should we try it again?

Yes, without the stable release these changes are useless.

**Comment by CAMOBAP** [comment]
Closed in favor of https://github.com/metanorma/packed-mn/pull/73

**Pull request closed without merging**
