### PR TITLE
Feature/samples test

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #31

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP since the builds are taking long, I think you should split the build into multiple tests that can be run in parallel.

i.e.:

1. Build and upload built artifact
2. Download built artifact, multiple parallel stages for tests per flavor

**Comment by CAMOBAP** [comment]
@ronaldtse done

@ronaldtse @w00lf please review the PR

**Comment by ronaldtse** [comment]
Thanks @camobap!! For the tests, I think we should have one process “per flavor” instead of all in background jobs, because there are not so many cores on GHA systems. It’s also slightly easier to manage?

**Comment by ronaldtse** [comment]
Also it allows better caching of Relaton entries than running all jobs at once in background.

**Pull request merged**
