### PR TITLE
#28 change metanorma-cli version provision approach

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
how it works shortly speaking
1. release on metanorma-cli trigger release.yml workflow
2. release.yml workflow:
   - modify Gemfile & Gemfile.lock
   - commit Gemfile & Gemfile.lock
   - do tag
   - push changes
3. The push which was done by release.yml workflow trigger osx & Linux, which will do actual release

@w00lf @ronaldtse  please let me know how do you think about this new approach

**Comment by ronaldtse** [comment]
@CAMOBAP the flow looks fine with me. I noticed your name has changed... 😉

**Comment by w00lf** [comment]
> how it works shortly speaking
> 
> 1. release on metanorma-cli trigger release.yml workflow
> 2. release.yml workflow:
>    
>    * modify Gemfile & Gemfile.lock
>    * commit Gemfile & Gemfile.lock
>    * do tag
>    * push changes
> 3. The push which was done by release.yml workflow trigger osx & Linux, which will do actual release
> 
> @w00lf @ronaldtse please let me know how do you think about this new approach
> 
> P.S. we still have option to do release manually, just by pushing tag

I think it can be done even simplier:

```
$: bundle remove metanorma-cli
$: bundle add metanorma-cli -v {$GIT_RELEASE_VERSION}
```

**Comment by CAMOBAP** [comment]
@w00lf thanks for the suggestion, your approach is definitely better from all point of view

**Pull request merged**
