### PR TITLE
Feature/upgrade bundler to 2.3+

### PR DESCRIPTION
**Pull request by maxirmx**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

Bundler upgrade to 2.3.15
Tebako upgrade to 0.3.7 (packaging fixes for multiple gems)
ruby-packer legacy cleaned from Makefile

### CODE REVIEW

**Review by CAMOBAP — APPROVED** [review]
Good Job!

**Comment by bradreeves94** [comment]
im sorry to ask but how do i update the bundler from 2.1.4 to the latest version

**Comment by ronaldtse** [comment]
@bradreeves94 thanks for the message. Are you asking about bundler with regards to the Metanorma executable, or in a generic Ruby context?

**Comment by CAMOBAP** [comment]
As far as I see according to screenshots this question related to general ruby context (not to packed-mn)

@bradreeves94 could you please try `sudo gem update bundler`

**Comment by bradreeves94** [comment]
Yes of course,

**Comment by bradreeves94** [comment]
Thank you sir, that did the job. I'm updated to 2.4.12

**Comment by bradreeves94** [comment]
I'm sorry about you but I'm kinda just getting into this is there any way you can help me out wink wink

**Comment by ronaldtse** [comment]
@bradreeves94 This repository is actually only to support the Metanorma executable -- if you have questions about Ruby or Bundler, you can file issues to:
* https://github.com/ruby/ruby
* https://github.com/rubygems/rubygems

**Pull request merged**
