### PR TITLE
Pinned ffi-compiler2 version to 2.0.1

### PR DESCRIPTION
**Pull request by maxirmx**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

Workaround for https://github.com/metanorma/ruby-libmspack/issues

### CODE REVIEW

**Review by CAMOBAP — APPROVED** [review]

**Comment by maxirmx** [comment]
Some tesst are failing because of https://github.com/metanorma/packed-mn/issues/222

**Comment by maxirmx** [comment]
I will go patch excavate as libmspack is used by it.
Otherwise all 'intermediate' build we keep failing (fontist, etc ...)

**Comment by ronaldtse** [comment]
Is there any code to upstream here?

**Comment by maxirmx** [comment]
> Is there any code to upstream here?

There is a change in ```ffi_compiler2``` and this change is not portable.
My best thought is to use ```mini_portile``` instead of ```ffi_compiler2``` but I believe it needs to be pre-approved.

**Comment by ronaldtse** [comment]
Sorry @maxirmx I don’t understand what “pre-approved” means here.

**Comment by maxirmx** [comment]
> Sorry @maxirmx I don’t understand what “pre-approved” means here.

I mean that ruby-libmspack maintainer should be ready to accept PR that changes build system and it would good to discuss it in advance

**Comment by maxirmx** [comment]
This PR shall cover all gems that use excavate
https://github.com/fontist/excavate/pull/26

**Comment by maxirmx** [comment]
Closing this PR since excavate path closes the issue
It is a temporary solution anyway. Long term we need a fix in ruby-libmspack.

**Pull request closed without merging**
