### PR TITLE
Test Gemfile.lock for *nix

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/mn-samples-iso/issues/58

### CODE REVIEW

**Comment by CAMOBAP** [comment]
> /__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1288:in `initialize': No such file or directory @ rb_sysopen - /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-libarchive-binary-0.2.2-x86_64-darwin/lib/ffi-libarchive-binary/libarchive.so.13.dylib (Errno::ENOENT)

reproduces only under ruby-packer

> /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.2.3/lib/excavate/archive.rb:65:in `extract_once': Could not unarchive `/home/runner/.fontist/downloads/d20210402-1575-hbh800/microsoft_excel_15.11.1_updater.pkg`. (Excavate::UnknownArchiveError)

Happens only on linux

**Comment by ronaldtse** [comment]
> /enclose_io_memfs/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.2.3/lib/excavate/archive.rb:65:in extract_once': Could not unarchive /home/runner/.fontist/downloads/d20210402-1575-hbh800/microsoft_excel_15.11.1_updater.pkg`. (Excavate::UnknownArchiveError)

I'm seeing this on annotated-express too, plain GHA.

**Comment by CAMOBAP** [comment]
@ronaldtse maybe you can post a link here (I cannot find this repo in our organizations) @alexmorozov maybe you have some info about this (can it be related to exclude`lz4` )

**Comment by ronaldtse** [comment]
@CAMOBAP this is the build:
https://github.com/metanorma/annotated-express/actions/runs/722123752

**Comment by CAMOBAP** [comment]
Two issues above fixed, new ones comes(:
 - [ ] missing gems for OCRA (windows exe)
 - [ ] /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.15.0/lib/ffi/struct_layout.rb:88:in `get': invalid memory read at address=0x00000000000000 (FFI::NullPointerError)

**Pull request closed without merging**
