### PR TITLE
#62 fix PDF generation command

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #62 

P.S. I have a problem with building it locally again(, for some reason compilation just hung on `compiling prelude.c`

I will do final tests on binary form CI

### CODE REVIEW

**Review by w00lf — APPROVED** [review]
lgtm

**Comment by ronaldtse** [comment]
Looks good @camobap — please merge when ready. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP does GHA now include PDF tests? We need to re-enable them. Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse just pushed the last changes 1 min ago, and once passed I will merge it and finish with the brew formula

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
Merging to see if it works.

**Pull request merged**
