### PR TITLE
#26 cleanum Gemfile

### PR DESCRIPTION
**Pull request by CAMOBAP**
- Once it will be merged upcoming release will be unblocked https://github.com/metanorma/metanorma-cli/issues/144#issuecomment-640869788

### CODE REVIEW

**Comment by CAMOBAP** [comment]
errors in `metanorma-iec` but `mn-samples-iec` works properly, IDK why

**Comment by CAMOBAP** [comment]
Looks like related to a late release of metanorma-iso, restarted

**Comment by CAMOBAP** [comment]
@ronaldtse @w00lf @opoudjis  maybe you have an idea why `bundle install` can installs `metanorma-iso 1.3.25` while `metanorma-iso 1.3.26` available?

**Comment by ronaldtse** [comment]
@camobap due to cache or gemspec  versioning?

**Comment by CAMOBAP** [comment]
It was my bad because of "frozen" old version of metanorma-cli

**Pull request merged**
