### PR TITLE
Migrate to ruby-packer 0.6.1

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/packed-mn/issues/113

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP you still need to do #111 due to the new metanorma version.

**Comment by CAMOBAP** [comment]
@ronaldtse good point, on the way, BTW we don't need mn2sts and sts2mn anymore, right?

**Comment by ronaldtse** [comment]
We don’t need those anymore because they are now superseded by mnconvert.

**Comment by CAMOBAP** [comment]
Failed samples:
 - nist - `Error: multiple instances of same ID`
 - iso - `Concept not cross-referencing term or symbol`
Investigation

**Comment by CAMOBAP** [comment]
@ronaldtse 

- NIST related issue reported in https://github.com/metanorma/mn-samples-nist/issues/65
- ISO doesn't reproduced on docker, still researching it

**Comment by CAMOBAP** [comment]
@ronaldtse 
 - I need help with I think I understand the root of the issue, but IDK how to fix it https://github.com/metanorma/mn-samples-nist/issues/65
 - ISO ready for review https://github.com/metanorma/mn-samples-iso/pull/78

**Comment by alexeymorozov** [comment]
Looks good to me :) Thanks for removal of the comments.

**Pull request merged**
